# ----- JVM / Gradle performance -----
org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configureondemand=true
org.gradle.workers.max=8

# ----- AndroidX / Jetifier (required by many libs) -----
android.useAndroidX=true
android.enableJetifier=true

# ----- R8 / Shrinker -----
# Leave R8 at default. Do NOT force resource/code shrinking here (we control it per buildType).
# android.enableR8=true            # (default)
# android.enableResourceOptimizations=false
# android.enableShrinkResources=false

# ----- Resource / R class optimizations (safe & faster builds) -----
android.nonTransitiveRClass=true
android.nonFinalResIds=true

# ----- Kotlin compiler -----
kotlin.code.style=official
kotlin.incremental=true
kotlin.daemon.jvmargs=-Xmx2G

# ----- Flutter specific defaults -----
# Keep BuildConfig enabled unless you explicitly disable in module config
android.defaults.buildfeatures.buildconfig=true
# This builtInKotlin flag was added automatically by Flutter migrator
android.builtInKotlin=false
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false
