// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFmKgbNpsADeJCxiVdt5aw0bHA3dwrWCo',
    appId: '1:502982299011:web:1bb40b2e563f0b6ff97ab6',
    messagingSenderId: '502982299011',
    projectId: 'xenchive-49864',
    authDomain: 'xenchive-49864.firebaseapp.com',
    storageBucket: 'xenchive-49864.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSsUNDro2eCQbxx8p04ojivwnhW_q0L_4',
    appId: '1:176930213940:android:2442ea1be7d476cfef3a61',
    messagingSenderId: '176930213940',
    projectId: 'xenchive-2f82b',
    storageBucket: 'xenchive-2f82b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdDq174iZxD3RxEbPLugtpvMZRjNNWklY',
    appId: '1:502982299011:ios:8ac58d346a739fe7f97ab6',
    messagingSenderId: '502982299011',
    projectId: 'xenchive-49864',
    storageBucket: 'xenchive-49864.firebasestorage.app',
    iosBundleId: 'com.example.xenchive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdDq174iZxD3RxEbPLugtpvMZRjNNWklY',
    appId: '1:502982299011:ios:8ac58d346a739fe7f97ab6',
    messagingSenderId: '502982299011',
    projectId: 'xenchive-49864',
    storageBucket: 'xenchive-49864.firebasestorage.app',
    iosBundleId: 'com.example.xenchive',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFmKgbNpsADeJCxiVdt5aw0bHA3dwrWCo',
    appId: '1:502982299011:web:a6169dcb11448d41f97ab6',
    messagingSenderId: '502982299011',
    projectId: 'xenchive-49864',
    authDomain: 'xenchive-49864.firebaseapp.com',
    storageBucket: 'xenchive-49864.firebasestorage.app',
  );

}