// lib/main.dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:cloud_firestore/cloud_firestore.dart';

// Screens
import 'features/landing/presentation/landing_screen.dart';
import 'features/auth/presentation/signin_screen.dart';
import 'features/auth/presentation/signup_screen.dart';

// Dashboards
import 'features/dashboard/presentation/student_dashboard.dart';
import 'features/dashboard/presentation/club_dashboard.dart';
import 'features/dashboard/presentation/faculty_dashboard.dart';
import 'features/dashboard/presentation/admin_dashboard.dart';

// CSRA tester (buttons to call your Functions)
import 'features/landing/presentation/csra_test_screen.dart';

// Firebase options (generated by `flutterfire configure`)
import 'firebase_options.dart';
import 'package:flutter/cupertino.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Edge-to-edge transparent system bars
  SystemChrome.setEnabledSystemUIMode(SystemUiMode.edgeToEdge);
  SystemChrome.setSystemUIOverlayStyle(
    const SystemUiOverlayStyle(
      statusBarColor: Colors.transparent,
      systemNavigationBarColor: Colors.transparent,
      systemNavigationBarDividerColor: Colors.transparent,
      statusBarIconBrightness: Brightness.light,
      systemNavigationBarIconBrightness: Brightness.light,
      statusBarBrightness: Brightness.dark,
      systemStatusBarContrastEnforced: false,
      systemNavigationBarContrastEnforced: false,
    ),
  );

  // Firebase init
  try {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
    debugPrint('✅ Firebase initialized');
  } catch (e) {
    debugPrint('❌ Firebase init failed: $e');
  }

  runApp(const XenchiveApp());
}

// ---------------- COLORS ----------------
class AppColors {
  static const midnightBlue = Color(0xFF0B1A30);
  static const obsidian = Color(0xFF0A0F16);
  static const porcelain = Color(0xFFF8F9FA);
  static const royalGold = Color(0xFFCBA135);
  static const platinum = Color(0xFFE2E6EA);
  static const azure = Color(0xFF3F8CFF);
  static const emerald = Color(0xFF3EB489);
}

// ---------------- THEME ----------------
ThemeData _buildTheme(Brightness brightness) {
  final isDark = brightness == Brightness.dark;

  final scheme = ColorScheme.fromSeed(
    seedColor: AppColors.midnightBlue,
    brightness: brightness,
    primary: isDark ? AppColors.royalGold : AppColors.midnightBlue,
    secondary: isDark ? AppColors.azure : AppColors.royalGold,
    surface: isDark ? AppColors.obsidian : AppColors.porcelain,
  );

  final base = ThemeData(
    useMaterial3: true,
    brightness: brightness,
    colorScheme: scheme,
    scaffoldBackgroundColor: scheme.surface,
    textTheme: GoogleFonts.plusJakartaSansTextTheme(),
    appBarTheme: const AppBarTheme(
      backgroundColor: Colors.transparent,
      surfaceTintColor: Colors.transparent,
      elevation: 0,
      centerTitle: true,
    ),
    pageTransitionsTheme: const PageTransitionsTheme(
      builders: {
        TargetPlatform.android: CupertinoPageTransitionsBuilder(),
        TargetPlatform.iOS: CupertinoPageTransitionsBuilder(),
        TargetPlatform.linux: FadeUpwardsPageTransitionsBuilder(),
        TargetPlatform.macOS: CupertinoPageTransitionsBuilder(),
        TargetPlatform.windows: FadeUpwardsPageTransitionsBuilder(),
      },
    ),
    inputDecorationTheme: InputDecorationTheme(
      filled: true,
      fillColor: isDark ? Colors.white.withOpacity(0.03) : Colors.white,
      border: OutlineInputBorder(
        borderRadius: BorderRadius.circular(14),
        borderSide: BorderSide(color: isDark ? Colors.white12 : Colors.black12),
      ),
      enabledBorder: OutlineInputBorder(
        borderRadius: BorderRadius.circular(14),
        borderSide: BorderSide(color: isDark ? Colors.white12 : Colors.black12),
      ),
      focusedBorder: OutlineInputBorder(
        borderRadius: BorderRadius.circular(14),
        borderSide: BorderSide(
          color: isDark ? AppColors.royalGold : AppColors.midnightBlue,
          width: 1.2,
        ),
      ),
      contentPadding: const EdgeInsets.symmetric(horizontal: 16, vertical: 14),
    ),
    elevatedButtonTheme: ElevatedButtonThemeData(
      style: ElevatedButton.styleFrom(
        backgroundColor: isDark ? AppColors.royalGold : AppColors.midnightBlue,
        foregroundColor: isDark ? Colors.black : Colors.white,
        padding: const EdgeInsets.symmetric(vertical: 14),
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
        elevation: 0,
      ),
    ),
    outlinedButtonTheme: OutlinedButtonThemeData(
      style: OutlinedButton.styleFrom(
        padding: const EdgeInsets.symmetric(vertical: 14),
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
        side: BorderSide(
          color: isDark ? Colors.white24 : Colors.black26,
          width: 1,
        ),
      ),
    ),
    textButtonTheme: TextButtonThemeData(
      style: TextButton.styleFrom(
        foregroundColor: isDark ? AppColors.royalGold : AppColors.midnightBlue,
      ),
    ),
  );

  return isDark
      ? base.copyWith(
          textTheme: GoogleFonts.plusJakartaSansTextTheme(base.textTheme).apply(
            bodyColor: AppColors.platinum,
            displayColor: AppColors.platinum,
          ),
        )
      : base;
}

// ---------------- ROOT APP ----------------
class XenchiveApp extends StatelessWidget {
  const XenchiveApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'XENCHIVE',
      debugShowCheckedModeBanner: false,
      theme: _buildTheme(Brightness.light),
      darkTheme: _buildTheme(Brightness.dark),
      themeMode: ThemeMode.system,

      // Edge-to-edge overlays for all routes
      builder: (context, child) {
        final isDark = Theme.of(context).brightness == Brightness.dark;
        final style =
            (isDark ? SystemUiOverlayStyle.light : SystemUiOverlayStyle.dark)
                .copyWith(
                  statusBarColor: Colors.transparent,
                  systemNavigationBarColor: Colors.transparent,
                  systemNavigationBarDividerColor: Colors.transparent,
                  systemStatusBarContrastEnforced: false,
                  systemNavigationBarContrastEnforced: false,
                );
        return AnnotatedRegion<SystemUiOverlayStyle>(
          value: style,
          child: child ?? const SizedBox.shrink(),
        );
      },

      // Auth gate controls initial screen
      home: const AuthGate(),
      //home: const CSRATestScreen(), // TEMP for testing
      // Named routes
      routes: {
        '/signin': (context) => const SignInScreen(),
        '/signup': (context) => const SignUpScreen(),
        '/studentDashboard': (context) => const StudentDashboard(),
        '/clubDashboard': (context) => const ClubDashboard(),
        '/facultyDashboard': (context) => const FacultyDashboard(),
        '/adminDashboard': (context) => const AdminDashboard(),

        // Tester to call your deployed Functions (open with: Navigator.pushNamed(context, '/csraTest'))
        '/csraTest': (context) => const CSRATestScreen(),
      },
      onUnknownRoute: (settings) =>
          MaterialPageRoute(builder: (_) => const ErrorScreen()),
      scrollBehavior: const _NoGlowScrollBehavior(),
    );
  }
}

// ---------------- AUTH GATE ----------------
class AuthGate extends StatelessWidget {
  const AuthGate({super.key});

  Future<String?> _fetchRole(User user) async {
    try {
      final doc = await FirebaseFirestore.instance
          .collection('users')
          .doc(user.uid)
          .get();

      if (!doc.exists) return null;

      final data = doc.data();
      if (data == null) return null;

      final role = data['role'];
      if (role is! String) return null;

      const allowed = ['Student', 'Club Lead', 'Faculty', 'Admin'];
      if (!allowed.contains(role)) return null;

      return role;
    } catch (e) {
      debugPrint('Role fetch error: $e');
      return null;
    }
  }

  Widget _routeForRole(String role) {
    switch (role) {
      case 'Student':
        return const StudentDashboard();
      case 'Club Lead':
        return const ClubDashboard();
      case 'Faculty':
        return const FacultyDashboard();
      case 'Admin':
        return const AdminDashboard();
      default:
        return const LandingScreen();
    }
  }

  @override
  Widget build(BuildContext context) {
    return StreamBuilder<User?>(
      stream: FirebaseAuth.instance.authStateChanges(),
      builder: (context, snap) {
        if (snap.connectionState == ConnectionState.waiting) {
          return const _Splash();
        }

        final user = snap.data;
        if (user == null) return const LandingScreen();

        return FutureBuilder<String?>(
          future: _fetchRole(user),
          builder: (context, roleSnap) {
            if (roleSnap.connectionState == ConnectionState.waiting) {
              return const _Splash();
            }

            final role = roleSnap.data;
            if (role == null) {
              FirebaseAuth.instance.signOut();
              return const LandingScreen();
            }

            return _routeForRole(role);
          },
        );
      },
    );
  }
}

// ---------------- SPLASH ----------------
class _Splash extends StatelessWidget {
  const _Splash();

  @override
  Widget build(BuildContext context) {
    final isDark = Theme.of(context).brightness == Brightness.dark;
    return Scaffold(
      backgroundColor: isDark ? AppColors.obsidian : AppColors.porcelain,
      body: const Center(
        child: SizedBox(
          width: 28,
          height: 28,
          child: CircularProgressIndicator(strokeWidth: 2.6),
        ),
      ),
    );
  }
}

// ---------------- ERROR SCREEN ----------------
class ErrorScreen extends StatelessWidget {
  const ErrorScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.red.shade50,
      body: Center(
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            Icon(
              Icons.warning_amber_rounded,
              color: Colors.red.shade700,
              size: 80,
            ),
            const SizedBox(height: 20),
            const Text(
              'Something went wrong!',
              style: TextStyle(fontSize: 22, fontWeight: FontWeight.bold),
            ),
            const SizedBox(height: 10),
            Text(
              'Please restart the app or check Firebase configuration.',
              textAlign: TextAlign.center,
              style: TextStyle(color: Colors.red.shade700),
            ),
          ],
        ),
      ),
    );
  }
}

// ---------------- SCROLL BEHAVIOR ----------------
class _NoGlowScrollBehavior extends MaterialScrollBehavior {
  const _NoGlowScrollBehavior();

  @override
  Widget buildOverscrollIndicator(
    BuildContext context,
    Widget child,
    ScrollableDetails details,
  ) {
    return child; // removes overscroll glow on Android
  }
}
